[package]
name = "bevy_spine"
version = "0.5.0"
edition = "2021"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/jabuwu/bevy_spine"
repository = "https://github.com/jabuwu/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
]

[dependencies]
rusty_spine = "0.5.2"
bevy = { version = "0.10", default-features = false, features = [ "bevy_render", "bevy_asset", "bevy_sprite" ] }
bevy_math = { version = "0.10", features = [ "mint" ] }
fixed_timestep = { path = "../fixed_timestep" }

[dev-dependencies]
lerp = "0.4"
bevy = { version = "0.10", default-features = true }

[features]
workaround_5732 = [] # enable to workaround Bevy issue #5732
